export const productPriceCatalog = [
  { name: 'Semaglutide Microdose, 2 months', price: 298 },
  { name: 'Semaglutide Starter package, 3 months', price: 597 },
  { name: 'Semaglutide Starter package, 6 months', price: 1014 },
  { name: 'Semaglutide Starter package, 12 months', price: 1788 },
  { name: 'Semaglutide Single purchase, 10 mg/1 month', price: 399 },
  { name: 'Tirzepatide Microdose, 2 months', price: 470 },
  { name: 'Tirzepatide Starter package, 3 months', price: 897 },
  { name: 'Tirzepatide Starter package, 6 months', price: 1494 },
  { name: 'Tirzepatide Starter package, 12 months', price: 2820 },
  { name: 'Tirzepatide Single purchase, 60 mg/1 month', price: 599 },
  { name: 'Lipo-Mino, 1 month', price: 374 },
  { name: 'Lipo-Mino, 3 months', price: 889 },
  { name: 'NAD+, 1 month', price: 374 },
  { name: 'NAD+, 3 months', price: 889 },
  { name: 'GHK-Cu, 1 month', price: 374 },
  { name: 'GHK-Cu, 3 months', price: 748 },
  { name: 'Sermorelin, 1 month', price: 374 },
  { name: 'Sermorelin, 2 months', price: 599 },
  { name: 'Glutathione, 2 months', price: 374 },
  { name: 'Glutathione, 4 months', price: 549 },
  { name: 'Nutrition Consultation, 1 month', price: 199 },
  { name: 'Nutrition Consultation, 1 month, non-GLP-1 client', price: 250 },
  { name: 'Nutrition Consultation, 3 months', price: 449.01 },
  { name: 'Nutrition Consultation, 6 months', price: 799.86 },
  { name: 'Nutrition Consultation, 12 months', price: 1379.16 },
  { name: 'Detox Tea', price: 15.99 },
  { name: 'Beauty Boost', price: 24.9 },
  { name: 'Bloat Away', price: 24.9 },
  { name: 'Bone & Heart Support', price: 24.9 },
  { name: 'Brain & Focus Formula', price: 24.9 },
  { name: 'Complete Multivitamin', price: 24.9 },
  { name: 'Detox Now', price: 24.9 },
  { name: 'Diet Drops Ultra', price: 24.9 },
  { name: 'Gut Boost', price: 24.9 },
  { name: 'Love Me Now/Maca Plus', price: 24.9 },
  { name: 'Omega-3', price: 24.9 },
  { name: 'Vitamin D3', price: 24.9 },
  { name: 'Magnesium Glycinate', price: 24.9 },
  { name: 'Energy Strips', price: 29.9 },
  { name: 'L-Glutamine Powder', price: 29.9 },
  { name: 'Sleep Strips', price: 29.9 },
  { name: 'Colon Gentle Cleanse', price: 33.9 },
  { name: 'Colostrum Capsules', price: 33.9 },
  { name: 'Creatine Monohydrate', price: 33.9 },
  { name: 'Fat Burner & Appetite Control', price: 33.9 },
  { name: 'Hydraglow Peach Mango', price: 34.99 },
  { name: 'Hydraglow Lychee', price: 34.99 },
  { name: 'Hydraglow Lemonade', price: 34.99 },
  { name: 'Apple Cider Vinegar Capsules', price: 39 },
  { name: 'Chocolate Collagen Peptides', price: 39.9 },
  { name: 'NAD+ Cellular Energy & Anti-Aging', price: 39.9 },
  { name: 'Unflavored Collagen Peptides', price: 39.9 },
  { name: 'Vanilla Collagen Peptides Creamer', price: 39.9 },
  { name: 'Berberine+', price: 45 },
  { name: 'GLP-1 Support', price: 45 },
  { name: 'Chocolate Whey Protein Isolate', price: 49.9 },
  { name: 'Vanilla Whey Protein Isolate', price: 49.9 },
  { name: 'SlimBoost', price: 89 },
  { name: 'Shipping', price: 5 },
]
