export const productPriceCatalog = [
  { name: 'Microdose Semaglutide – 2 Months', price: 298 },
  { name: 'Semaglutide Starter Package – 3 Months', price: 597 },
  { name: 'Semaglutide Starter Package – 6 Months', price: 1014 },
  { name: 'Semaglutide Starter Package – 12 Months', price: 1788 },
  { name: 'Semaglutide 10mg – 1 Month', price: 399 },
  { name: 'Microdose Tirzepatide – 2 Months', price: 470 },
  { name: 'Tirzepatide Starter Package – 3 Months', price: 897 },
  { name: 'Tirzepatide Starter Package – 6 Months', price: 1494 },
  { name: 'Tirzepatide Starter Package – 12 Months', price: 2820 },
  { name: 'Tirzepatide 60mg – 1 Month', price: 599 },
  { name: 'Lipo-Mino – 1 Month', price: 374 },
  { name: 'Lipo-Mino – 3 Months', price: 889 },
  { name: 'NAD+ – 1 Month', price: 374 },
  { name: 'NAD+ – 3 Months', price: 889 },
  { name: 'GHK-Cu – 1 Month', price: 374 },
  { name: 'GHK-Cu – 3 Months', price: 748 },
  { name: 'Sermorelin – 1 Month', price: 374 },
  { name: 'Sermorelin – 2 Months', price: 599 },
  { name: 'Glutathione – 2 Months', price: 374 },
  { name: 'Glutathione – 4 Months', price: 549 },
  { name: 'Nutrition Consultation – 1 Month', price: 199 },
  { name: 'Nutrition Consultation – 1 Month, Non-GLP-1 Clients', price: 250 },
  { name: 'Nutrition Consultation – 3 Months', price: 449.01 },
  { name: 'Nutrition Consultation – 6 Months', price: 799.86 },
  { name: 'Nutrition Consultation – 12 Months', price: 1379.16 },
  { name: 'Detox Tea', price: 15.99 },
  { name: 'Beauty Boost – Hair, Skin and Nails Essentials', price: 24.9 },
  { name: 'Bloat Away – Probiotic 40 Billion with Prebiotics', price: 24.9 },
  { name: 'Bone & Heart Support', price: 24.9 },
  { name: 'Brain & Focus Formula', price: 24.9 },
  { name: 'Complete Multivitamin', price: 24.9 },
  { name: 'Detox Now – Refresh, Cleanse & Glow', price: 24.9 },
  { name: 'Diet Drops Ultra', price: 24.9 },
  { name: 'Gut Boost Pro & Smooth Digestion', price: 24.9 },
  { name: 'Love Me Now – Maca Plus', price: 24.9 },
  { name: 'Omega-3 EPA 180mg + DHA 120mg', price: 24.9 },
  { name: 'Vitamin D3 2,000 IU', price: 24.9 },
  { name: 'Magnesium Glycinate', price: 24.9 },
  { name: 'Energy Strips', price: 29.9 },
  { name: 'L-Glutamine Powder', price: 29.9 },
  { name: 'Sleep Strips', price: 29.9 },
  { name: 'Colon Gentle Cleanse', price: 33.9 },
  { name: 'Colostrum Capsules', price: 33.9 },
  { name: 'Creatine Monohydrate', price: 33.9 },
  { name: 'Fat Burner & Appetite Control', price: 33.9 },
  { name: 'Hydraglow Powder – Peach Mango', price: 34.99 },
  { name: 'Hydraglow Powder – Lychee', price: 34.99 },
  { name: 'Hydraglow Powder – Lemonade', price: 34.99 },
  { name: 'Apple Cider Vinegar Capsules', price: 39 },
  { name: 'Chocolate Collagen Peptides Grass-Fed Powder', price: 39.9 },
  { name: 'NAD+ Cellular Energy & Anti-Aging', price: 39.9 },
  { name: 'Unflavored Collagen Peptides Hydrolyzed Grass-Fed', price: 39.9 },
  { name: 'Vanilla Collagen Peptides Creamer Grass-Fed Powder', price: 39.9 },
  { name: 'Berberine+ & Pierde Peso', price: 45 },
  { name: 'GLP-1 Support – Daily Metabolic, Gut & Micronutrient Formula', price: 45 },
  { name: 'Chocolate Whey Protein Isolate Advanced 100%', price: 49.9 },
  { name: 'Vanilla Whey Protein Isolate Advanced 100%', price: 49.9 },
  { name: 'SlimBoost', price: 89 },
  { name: 'Shipping', price: 5 },
]
